wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/README.txt
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/info.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_meta.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_meta.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_resized_256.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_resized_256.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/val_images_256.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/test_images_256.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/test_images.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/val_images.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_00.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_01.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_01.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_02.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_03.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_04.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_05.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_06.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_07.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_08.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_09.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_10.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_11.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_12.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_13.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_14.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_15.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/flickr_16.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_00.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_01.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_02.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_03.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_04.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_05.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_06.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_07.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_08.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_09.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_10.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_11.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_12.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_13.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_14.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_15.tar
wget -P /data3/zzhang/ours/webvision https://data.vision.ee.ethz.ch/cvl/webvision/google_16.tar